
#ifndef _COLOR_H_
#define _COLOR_H_

enum Color
{
	// BLACK BACKGROUND
	BLACK = 0,
	BLUE = 1,
	GREEN = 2,
	CYAN = 3,
	RED = 4,
	MAGENTA = 5,
	BROWN = 6,
	LIGHTGREY = 7,
	DARKGREY = 8,
	LIGHTBLUE = 9,
	LIGHTGREEN = 10,
	LIGHTCYAN = 11,
	LIGHTRED = 12,
	LIGHTMAGENTA = 13,
	YELLOW = 14,
	WHITE = 15,

	// COLORED BACKGROUND
	WHITEONBLUE = BLUE<<4 | WHITE,
	LIGHTMAGENTAONBLUE =BLUE << 4 | LIGHTMAGENTA,
	LIGHTGREYONBLUE = BLUE << 4 | LIGHTGREY,
	LIGHTGREY_BACK = LIGHTGREY << 4 | LIGHTGREY,
	DARKGREY_BACK = DARKGREY << 4 | DARKGREY,
	LIGHTGREENONBLUE = BLUE << 4 | LIGHTGREEN,
	YELLOWONBLUE = BLUE << 4 | YELLOW,
	BLUE_BACK = BLUE << 4 | BLUE,
	WHITEONMAGENTA = MAGENTA << 4 | WHITE,
	MAGENTA_BACK = MAGENTA << 4 | MAGENTA,
	LIGHTGREENONMAGENTA = MAGENTA << 4 | LIGHTGREEN,
	YELLOWONMAGENTA = MAGENTA << 4 | YELLOW,
	BLACKONGREY= DARKGREY << 4 | BLACK,
	BLACKONBLUE = BLUE << 4 | BLACK

};

#endif